// Generated by: pnpm db:types (snapshot fallback)
// Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string;
          created_at: string;
          entity_id: string;
          entity_type: string;
          id: string;
          org_id: string;
          payload: Json;
          store_id: string | null;
          user_id: string | null;
        };
        Insert: {
          action: string;
          created_at?: string;
          entity_id: string;
          entity_type: string;
          id?: string;
          org_id: string;
          payload?: Json;
          store_id?: string | null;
          user_id?: string | null;
        };
        Update: {
          action?: string;
          created_at?: string;
          entity_id?: string;
          entity_type?: string;
          id?: string;
          org_id?: string;
          payload?: Json;
          store_id?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          created_at: string;
          id: string;
          is_active: boolean;
          name: string;
          org_id: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name: string;
          org_id: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name?: string;
          org_id?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          created_at: string;
          document: string | null;
          email: string | null;
          id: string;
          name: string;
          org_id: string;
          phone: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          document?: string | null;
          email?: string | null;
          id?: string;
          name: string;
          org_id: string;
          phone?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          document?: string | null;
          email?: string | null;
          id?: string;
          name?: string;
          org_id?: string;
          phone?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      fiscal_documents: {
        Row: {
          adapter: string;
          created_at: string;
          external_id: string | null;
          id: string;
          org_id: string;
          payload: Json;
          sale_id: string;
          status: Database["public"]["Enums"]["fiscal_document_status"];
          updated_at: string;
        };
        Insert: {
          adapter?: string;
          created_at?: string;
          external_id?: string | null;
          id?: string;
          org_id: string;
          payload?: Json;
          sale_id: string;
          status?: Database["public"]["Enums"]["fiscal_document_status"];
          updated_at?: string;
        };
        Update: {
          adapter?: string;
          created_at?: string;
          external_id?: string | null;
          id?: string;
          org_id?: string;
          payload?: Json;
          sale_id?: string;
          status?: Database["public"]["Enums"]["fiscal_document_status"];
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory_balances: {
        Row: {
          id: string;
          org_id: string;
          product_id: string;
          quantity: number;
          store_id: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          product_id: string;
          quantity?: number;
          store_id: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          product_id?: string;
          quantity?: number;
          store_id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory_movements: {
        Row: {
          balance_after: number;
          created_at: string;
          created_by: string;
          id: string;
          movement_type: Database["public"]["Enums"]["inventory_movement_type"];
          org_id: string;
          product_id: string;
          quantity_change: number;
          reason: string | null;
          actor_role: Database["public"]["Enums"]["member_role"] | null;
          sale_id: string | null;
          store_id: string;
        };
        Insert: {
          balance_after: number;
          created_at?: string;
          created_by: string;
          id?: string;
          movement_type: Database["public"]["Enums"]["inventory_movement_type"];
          org_id: string;
          product_id: string;
          quantity_change: number;
          reason?: string | null;
          actor_role?: Database["public"]["Enums"]["member_role"] | null;
          sale_id?: string | null;
          store_id: string;
        };
        Update: {
          balance_after?: number;
          created_at?: string;
          created_by?: string;
          id?: string;
          movement_type?: Database["public"]["Enums"]["inventory_movement_type"];
          org_id?: string;
          product_id?: string;
          quantity_change?: number;
          reason?: string | null;
          actor_role?: Database["public"]["Enums"]["member_role"] | null;
          sale_id?: string | null;
          store_id?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          created_at: string;
          currency: string;
          id: string;
          name: string;
          slug: string;
          timezone: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency?: string;
          id?: string;
          name: string;
          slug: string;
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          id?: string;
          name?: string;
          slug?: string;
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          adapter_status: Database["public"]["Enums"]["adapter_status"];
          amount: number;
          created_at: string;
          external_reference: string | null;
          id: string;
          method: Database["public"]["Enums"]["payment_method"];
          org_id: string;
          sale_id: string;
          status: Database["public"]["Enums"]["payment_status"];
        };
        Insert: {
          adapter_status?: Database["public"]["Enums"]["adapter_status"];
          amount: number;
          created_at?: string;
          external_reference?: string | null;
          id?: string;
          method: Database["public"]["Enums"]["payment_method"];
          org_id: string;
          sale_id: string;
          status?: Database["public"]["Enums"]["payment_status"];
        };
        Update: {
          adapter_status?: Database["public"]["Enums"]["adapter_status"];
          amount?: number;
          created_at?: string;
          external_reference?: string | null;
          id?: string;
          method?: Database["public"]["Enums"]["payment_method"];
          org_id?: string;
          sale_id?: string;
          status?: Database["public"]["Enums"]["payment_status"];
        };
        Relationships: [];
      };
      products: {
        Row: {
          barcode: string | null;
          category_id: string | null;
          cost_price: number;
          created_at: string;
          description: string | null;
          id: string;
          is_active: boolean;
          name: string;
          org_id: string;
          sku: string;
          unit_price: number;
          updated_at: string;
        };
        Insert: {
          barcode?: string | null;
          category_id?: string | null;
          cost_price?: number;
          created_at?: string;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          name: string;
          org_id: string;
          sku: string;
          unit_price: number;
          updated_at?: string;
        };
        Update: {
          barcode?: string | null;
          category_id?: string | null;
          cost_price?: number;
          created_at?: string;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          name?: string;
          org_id?: string;
          sku?: string;
          unit_price?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          created_at: string;
          default_role: Database["public"]["Enums"]["member_role"];
          email: string;
          full_name: string;
          id: string;
          org_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          default_role?: Database["public"]["Enums"]["member_role"];
          email: string;
          full_name: string;
          id: string;
          org_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          default_role?: Database["public"]["Enums"]["member_role"];
          email?: string;
          full_name?: string;
          id?: string;
          org_id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sale_idempotency_keys: {
        Row: {
          client_mutation_id: string;
          created_at: string;
          sale_id: string;
          store_id: string;
        };
        Insert: {
          client_mutation_id: string;
          created_at?: string;
          sale_id: string;
          store_id: string;
        };
        Update: {
          client_mutation_id?: string;
          created_at?: string;
          sale_id?: string;
          store_id?: string;
        };
        Relationships: [];
      };
      sale_items: {
        Row: {
          created_at: string;
          discount: number;
          id: string;
          product_id: string;
          product_name: string;
          product_sku: string;
          quantity: number;
          sale_id: string;
          total: number;
          unit_price: number;
        };
        Insert: {
          created_at?: string;
          discount?: number;
          id?: string;
          product_id: string;
          product_name: string;
          product_sku: string;
          quantity: number;
          sale_id: string;
          total: number;
          unit_price: number;
        };
        Update: {
          created_at?: string;
          discount?: number;
          id?: string;
          product_id?: string;
          product_name?: string;
          product_sku?: string;
          quantity?: number;
          sale_id?: string;
          total?: number;
          unit_price?: number;
        };
        Relationships: [];
      };
      sales: {
        Row: {
          cashier_id: string;
          client_mutation_id: string;
          confirmed_at: string | null;
          created_at: string;
          customer_id: string | null;
          discount: number;
          id: string;
          notes: string | null;
          org_id: string;
          status: Database["public"]["Enums"]["sale_status"];
          store_id: string;
          subtotal: number;
          sync_status: Database["public"]["Enums"]["sync_status"];
          total: number;
          updated_at: string;
        };
        Insert: {
          cashier_id: string;
          client_mutation_id: string;
          confirmed_at?: string | null;
          created_at?: string;
          customer_id?: string | null;
          discount?: number;
          id?: string;
          notes?: string | null;
          org_id: string;
          status?: Database["public"]["Enums"]["sale_status"];
          store_id: string;
          subtotal?: number;
          sync_status?: Database["public"]["Enums"]["sync_status"];
          total?: number;
          updated_at?: string;
        };
        Update: {
          cashier_id?: string;
          client_mutation_id?: string;
          confirmed_at?: string | null;
          created_at?: string;
          customer_id?: string | null;
          discount?: number;
          id?: string;
          notes?: string | null;
          org_id?: string;
          status?: Database["public"]["Enums"]["sale_status"];
          store_id?: string;
          subtotal?: number;
          sync_status?: Database["public"]["Enums"]["sync_status"];
          total?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      store_members: {
        Row: {
          created_at: string;
          id: string;
          org_id: string;
          role: Database["public"]["Enums"]["member_role"];
          store_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          org_id: string;
          role: Database["public"]["Enums"]["member_role"];
          store_id: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          org_id?: string;
          role?: Database["public"]["Enums"]["member_role"];
          store_id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      stores: {
        Row: {
          code: string;
          created_at: string;
          id: string;
          is_active: boolean;
          name: string;
          org_id: string;
          updated_at: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name: string;
          org_id: string;
          updated_at?: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name?: string;
          org_id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      process_sale: {
        Args: { p_payload: Json };
        Returns: Json;
      };
      process_sale_core: {
        Args: { p_payload: Json };
        Returns: Json;
      };
      assert_sale_discount_cap: {
        Args: { p_store_id: string; p_discount: number; p_subtotal: number };
        Returns: undefined;
      };
      adjust_inventory: {
        Args: { p_payload: Json };
        Returns: Json;
      };
      get_dashboard_metrics: {
        Args: { p_payload: Json };
        Returns: Json;
      };
      get_inventory_page: {
        Args: { p_payload: Json };
        Returns: Json;
      };
      current_user_org_id: { Args: Record<string, never>; Returns: string };
      user_has_store_access: { Args: { p_store_id: string }; Returns: boolean };
      user_store_role: { Args: { p_store_id: string }; Returns: Database["public"]["Enums"]["member_role"] };
      user_can_manage_inventory: { Args: { p_store_id: string }; Returns: boolean };
      user_can_view_reports: { Args: { p_store_id: string }; Returns: boolean };
    };
    Enums: {
      adapter_status: "configured" | "not_configured" | "error";
      fiscal_document_status: "not_configured" | "pending" | "issued" | "failed" | "cancelled";
      inventory_movement_type: "sale" | "refund" | "restock" | "adjustment";
      member_role: "admin" | "cashier" | "manager";
      payment_method: "cash" | "card" | "pix" | "voucher" | "other";
      payment_status: "pending" | "authorized" | "captured" | "failed" | "cancelled" | "refunded";
      sale_status: "draft" | "pending_sync" | "confirmed" | "cancelled" | "refunded" | "partially_refunded";
      sync_status: "pending" | "processing" | "synced" | "failed" | "conflict";
    };
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];

export type ProcessSaleResult = {
  sale_id: string;
  replay: boolean;
  status: Enums<"sale_status">;
  total?: string;
};
