// Generated by: pnpm db:types
// Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string
          created_at: string
          entity_id: string
          entity_type: string
          id: string
          org_id: string
          payload: Json
          store_id: string
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
          org_id: string
          payload?: Json
          store_id: string
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
          org_id?: string
          payload?: Json
          store_id?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_audit_logs_store_org"
            columns: ["store_id", "org_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id", "org_id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          name: string
          org_id: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          org_id: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          org_id?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          created_at: string
          document: string | null
          email: string | null
          id: string
          name: string
          org_id: string
          phone: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          document?: string | null
          email?: string | null
          id?: string
          name: string
          org_id: string
          phone?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          document?: string | null
          email?: string | null
          id?: string
          name?: string
          org_id?: string
          phone?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      fiscal_documents: {
        Row: {
          adapter: string
          created_at: string
          external_id: string | null
          id: string
          org_id: string
          payload: Json
          sale_id: string
          status: Database["public"]["Enums"]["fiscal_document_status"]
          store_id: string
          updated_at: string
        }
        Insert: {
          adapter?: string
          created_at?: string
          external_id?: string | null
          id?: string
          org_id: string
          payload?: Json
          sale_id: string
          status?: Database["public"]["Enums"]["fiscal_document_status"]
          store_id: string
          updated_at?: string
        }
        Update: {
          adapter?: string
          created_at?: string
          external_id?: string | null
          id?: string
          org_id?: string
          payload?: Json
          sale_id?: string
          status?: Database["public"]["Enums"]["fiscal_document_status"]
          store_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fiscal_documents_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fiscal_documents_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: true
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_fiscal_documents_sale_store_org"
            columns: ["sale_id", "store_id", "org_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id", "store_id", "org_id"]
          },
        ]
      }
      inventory_balances: {
        Row: {
          id: string
          org_id: string
          product_id: string
          quantity: number
          store_id: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          product_id: string
          quantity?: number
          store_id: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          product_id?: string
          quantity?: number
          store_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_balances_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_balances_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_balances_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_movements: {
        Row: {
          actor_role: Database["public"]["Enums"]["member_role"] | null
          balance_after: number
          created_at: string
          created_by: string
          id: string
          movement_type: Database["public"]["Enums"]["inventory_movement_type"]
          org_id: string
          product_id: string
          quantity_change: number
          reason: string | null
          sale_id: string | null
          store_id: string
        }
        Insert: {
          actor_role?: Database["public"]["Enums"]["member_role"] | null
          balance_after: number
          created_at?: string
          created_by: string
          id?: string
          movement_type: Database["public"]["Enums"]["inventory_movement_type"]
          org_id: string
          product_id: string
          quantity_change: number
          reason?: string | null
          sale_id?: string | null
          store_id: string
        }
        Update: {
          actor_role?: Database["public"]["Enums"]["member_role"] | null
          balance_after?: number
          created_at?: string
          created_by?: string
          id?: string
          movement_type?: Database["public"]["Enums"]["inventory_movement_type"]
          org_id?: string
          product_id?: string
          quantity_change?: number
          reason?: string | null
          sale_id?: string | null
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_movements_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          currency: string
          id: string
          name: string
          slug: string
          timezone: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          currency?: string
          id?: string
          name: string
          slug: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          currency?: string
          id?: string
          name?: string
          slug?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      payments: {
        Row: {
          adapter_status: Database["public"]["Enums"]["adapter_status"]
          amount: number
          created_at: string
          external_reference: string | null
          id: string
          method: Database["public"]["Enums"]["payment_method"]
          org_id: string
          sale_id: string
          status: Database["public"]["Enums"]["payment_status"]
        }
        Insert: {
          adapter_status?: Database["public"]["Enums"]["adapter_status"]
          amount: number
          created_at?: string
          external_reference?: string | null
          id?: string
          method: Database["public"]["Enums"]["payment_method"]
          org_id: string
          sale_id: string
          status?: Database["public"]["Enums"]["payment_status"]
        }
        Update: {
          adapter_status?: Database["public"]["Enums"]["adapter_status"]
          amount?: number
          created_at?: string
          external_reference?: string | null
          id?: string
          method?: Database["public"]["Enums"]["payment_method"]
          org_id?: string
          sale_id?: string
          status?: Database["public"]["Enums"]["payment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "payments_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          barcode: string | null
          category_id: string | null
          cost_price: number
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          name: string
          org_id: string
          sku: string
          unit_price: number
          updated_at: string
        }
        Insert: {
          barcode?: string | null
          category_id?: string | null
          cost_price?: number
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name: string
          org_id: string
          sku: string
          unit_price: number
          updated_at?: string
        }
        Update: {
          barcode?: string | null
          category_id?: string | null
          cost_price?: number
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name?: string
          org_id?: string
          sku?: string
          unit_price?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          default_role: Database["public"]["Enums"]["member_role"]
          email: string
          full_name: string
          id: string
          org_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          default_role?: Database["public"]["Enums"]["member_role"]
          email: string
          full_name: string
          id: string
          org_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          default_role?: Database["public"]["Enums"]["member_role"]
          email?: string
          full_name?: string
          id?: string
          org_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      sale_idempotency_keys: {
        Row: {
          client_mutation_id: string
          created_at: string
          sale_id: string
          store_id: string
        }
        Insert: {
          client_mutation_id: string
          created_at?: string
          sale_id: string
          store_id: string
        }
        Update: {
          client_mutation_id?: string
          created_at?: string
          sale_id?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sale_idempotency_keys_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sale_idempotency_keys_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      sale_items: {
        Row: {
          created_at: string
          discount: number
          id: string
          product_id: string
          product_name: string
          product_sku: string
          quantity: number
          sale_id: string
          total: number
          unit_price: number
        }
        Insert: {
          created_at?: string
          discount?: number
          id?: string
          product_id: string
          product_name: string
          product_sku: string
          quantity: number
          sale_id: string
          total: number
          unit_price: number
        }
        Update: {
          created_at?: string
          discount?: number
          id?: string
          product_id?: string
          product_name?: string
          product_sku?: string
          quantity?: number
          sale_id?: string
          total?: number
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "sale_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sale_items_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      sales: {
        Row: {
          cashier_id: string
          client_mutation_id: string
          confirmed_at: string | null
          created_at: string
          customer_id: string | null
          discount: number
          id: string
          notes: string | null
          org_id: string
          status: Database["public"]["Enums"]["sale_status"]
          store_id: string
          subtotal: number
          sync_status: Database["public"]["Enums"]["sync_status"]
          total: number
          updated_at: string
        }
        Insert: {
          cashier_id: string
          client_mutation_id: string
          confirmed_at?: string | null
          created_at?: string
          customer_id?: string | null
          discount?: number
          id?: string
          notes?: string | null
          org_id: string
          status?: Database["public"]["Enums"]["sale_status"]
          store_id: string
          subtotal?: number
          sync_status?: Database["public"]["Enums"]["sync_status"]
          total?: number
          updated_at?: string
        }
        Update: {
          cashier_id?: string
          client_mutation_id?: string
          confirmed_at?: string | null
          created_at?: string
          customer_id?: string | null
          discount?: number
          id?: string
          notes?: string | null
          org_id?: string
          status?: Database["public"]["Enums"]["sale_status"]
          store_id?: string
          subtotal?: number
          sync_status?: Database["public"]["Enums"]["sync_status"]
          total?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      store_members: {
        Row: {
          created_at: string
          id: string
          org_id: string
          role: Database["public"]["Enums"]["member_role"]
          store_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          org_id: string
          role: Database["public"]["Enums"]["member_role"]
          store_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          org_id?: string
          role?: Database["public"]["Enums"]["member_role"]
          store_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "fk_store_members_store_same_org"
            columns: ["store_id", "org_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id", "org_id"]
          },
          {
            foreignKeyName: "store_members_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "store_members_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      stores: {
        Row: {
          code: string
          created_at: string
          id: string
          is_active: boolean
          name: string
          org_id: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          org_id: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          org_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "stores_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      adjust_inventory: { Args: { p_payload: Json }; Returns: Json }
      assert_sale_discount_cap: {
        Args: { p_discount: number; p_store_id: string; p_subtotal: number }
        Returns: undefined
      }
      assert_sale_payload_integrity: {
        Args: { p_payload: Json }
        Returns: undefined
      }
      category_belongs_to_org: {
        Args: { p_category_id: string; p_org_id: string }
        Returns: boolean
      }
      create_product: {
        Args: { p_payload: Json; p_store_id: string }
        Returns: Json
      }
      current_user_org_id: { Args: never; Returns: string }
      get_dashboard_metrics: { Args: { p_payload: Json }; Returns: Json }
      get_inventory_page: { Args: { p_payload: Json }; Returns: Json }
      process_sale: { Args: { p_payload: Json }; Returns: Json }
      process_sale_core: { Args: { p_payload: Json }; Returns: Json }
      sale_payload_matches: {
        Args: { p_payload: Json; p_sale_id: string }
        Returns: boolean
      }
      update_product: {
        Args: { p_payload: Json; p_product_id: string; p_store_id: string }
        Returns: Json
      }
      user_can_manage_inventory: {
        Args: { p_store_id: string }
        Returns: boolean
      }
      user_can_view_reports: { Args: { p_store_id: string }; Returns: boolean }
      user_has_org_role: {
        Args: {
          p_roles: Database["public"]["Enums"]["member_role"][]
          p_store_id: string
        }
        Returns: boolean
      }
      user_has_store_access: { Args: { p_store_id: string }; Returns: boolean }
      user_store_role: {
        Args: { p_store_id: string }
        Returns: Database["public"]["Enums"]["member_role"]
      }
    }
    Enums: {
      adapter_status: "configured" | "not_configured" | "error"
      fiscal_document_status:
        | "not_configured"
        | "pending"
        | "issued"
        | "failed"
        | "cancelled"
      inventory_movement_type: "sale" | "refund" | "restock" | "adjustment"
      member_role: "admin" | "cashier" | "manager"
      payment_method: "cash" | "card" | "pix" | "voucher" | "other"
      payment_status:
        | "pending"
        | "authorized"
        | "captured"
        | "failed"
        | "cancelled"
        | "refunded"
      sale_status:
        | "draft"
        | "pending_sync"
        | "confirmed"
        | "cancelled"
        | "refunded"
        | "partially_refunded"
      sync_status: "pending" | "processing" | "synced" | "failed" | "conflict"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      adapter_status: ["configured", "not_configured", "error"],
      fiscal_document_status: [
        "not_configured",
        "pending",
        "issued",
        "failed",
        "cancelled",
      ],
      inventory_movement_type: ["sale", "refund", "restock", "adjustment"],
      member_role: ["admin", "cashier", "manager"],
      payment_method: ["cash", "card", "pix", "voucher", "other"],
      payment_status: [
        "pending",
        "authorized",
        "captured",
        "failed",
        "cancelled",
        "refunded",
      ],
      sale_status: [
        "draft",
        "pending_sync",
        "confirmed",
        "cancelled",
        "refunded",
        "partially_refunded",
      ],
      sync_status: ["pending", "processing", "synced", "failed", "conflict"],
    },
  },
} as const
